package estimator

import (
	"math"
	"testing"

	"github.com/llm-inferno/queue-analysis/pkg/analyzer"
)

// mkObs builds a fitObservation whose TTFT/ITL are generated by the queue analyzer at
// params x, so the observation is self-consistent and lies on a valid operating point.
func mkObs(t *testing.T, x []float64, lambdaRPM float64, inTok, outTok float32, maxBatch, maxQ int) fitObservation {
	t.Helper()
	qa, err := analyzer.NewLLMQueueAnalyzer(&analyzer.Configuration{
		MaxBatchSize: maxBatch,
		MaxQueueSize: maxQ,
		ServiceParms: &analyzer.ServiceParms{Alpha: float32(x[0]), Beta: float32(x[1]), Gamma: float32(x[2])},
	}, &analyzer.RequestSize{AvgInputTokens: inTok, AvgOutputTokens: outTok})
	if err != nil {
		t.Fatalf("analyzer setup failed at inTok=%v lambda=%v: %v", inTok, lambdaRPM, err)
	}
	m, err := qa.Analyze(float32(lambdaRPM / 60))
	if err != nil {
		t.Fatalf("analyze failed at inTok=%v lambda=%v: %v", inTok, lambdaRPM, err)
	}
	return fitObservation{
		Lambda:          lambdaRPM,
		MaxBatch:        maxBatch,
		MaxQueueSize:    maxQ,
		AvgInputTokens:  inTok,
		AvgOutputTokens: outTok,
		AvgTTFT:         float64(m.AvgTTFT),
		AvgITL:          float64(m.AvgTokenTime),
	}
}

// A window whose observations all sit at the same operating point cannot identify
// beta and gamma separately: every row of the residual Jacobian is identical, so the
// condition number is effectively infinite. A window spanning a range of token sizes
// excites the parameters and yields a small, finite condition number.
func TestFitConditionNumber_LargeForCollinearWindow(t *testing.T) {
	x := []float64{8.0, 0.016, 0.0005}

	collinear := []fitObservation{
		mkObs(t, x, 15, 2000, 1000, 128, 2048),
		mkObs(t, x, 15, 2000, 1000, 128, 2048),
		mkObs(t, x, 15, 2000, 1000, 128, 2048),
	}
	excited := []fitObservation{
		mkObs(t, x, 12, 500, 400, 128, 2048),
		mkObs(t, x, 15, 1500, 1000, 128, 2048),
		mkObs(t, x, 18, 2500, 1600, 128, 2048),
	}

	kCollinear := fitConditionNumber(collinear, x)
	kExcited := fitConditionNumber(excited, x)

	if !(kExcited < kCollinear) {
		t.Fatalf("expected excited condition number (%g) < collinear (%g)", kExcited, kCollinear)
	}
	// The collinear window must be flagged as effectively unidentifiable.
	if kCollinear < 1e6 {
		t.Fatalf("expected collinear condition number >= 1e6, got %g", kCollinear)
	}
	// The well-excited window must be comfortably identifiable.
	if math.IsInf(kExcited, 0) || kExcited > 1e4 {
		t.Fatalf("expected excited condition number to be finite and < 1e4, got %g", kExcited)
	}
}
