apiVersion: v1
kind: ConfigMap
metadata:
  name: model-tuner-config
  labels:
    app: model-tuner
data:
  default-config-data.json: |
    {
        "filterData": {
            "gammaFactor": 1.0,
            "errorLevel": 0.05,
            "tPercentile": 1.96
        },
        "modelData": {
            "initState": [
                10.0,
                0.02,
                0.0001
            ],
            "percentChange": [
                0.25,
                0.25,
                0.25
            ],
            "boundedState": true,
            "minState": [
                4.0,
                0.002,
                0.00001
            ],
            "maxState": [
                100,
                0.2,
                0.001
            ],
            "expectedObservations": [
                200.0,
                40.0
            ]
        }
