apiVersion: v1
kind: ConfigMap
metadata:
  name: model-tuner-config
  namespace: inferno
  labels:
    app: model-tuner
data:
  default-config-data.json: |
    {
        "filterData": {
            "gammaFactor": 1.0,
            "errorLevel": 0.5,
            "tPercentile": 1.96
        },
        "modelData": {
            "initState": [
                5.0,
                0.05,
                0.00005
            ],
            "percentChange": [
                0.15,
                0.15,
                0.15
            ],
            "boundedState": true,
            "minState": [
                0.05,
                0.0005,
                0.0000005
            ],
            "maxState": [
                500.0,
                5.0,
                0.005
            ],
            "expectedObservations": [
                200.0,
                40.0
            ]
        }
    }
